//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResourcingTool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        public int ProjectId { get; set; }
        public string ProjectName { get; set; }
        public string ProjectSector { get; set; }
        public string ProjectClient { get; set; }
        public string ProjectLead { get; set; }
        public string ProjectNature { get; set; }
        public string ProjectScope { get; set; }
        public System.DateTime ContractStart { get; set; }
        public System.DateTime ContractFinish { get; set; }
        public System.DateTime Briefing { get; set; }
        public System.DateTime Fieldwork { get; set; }
        public System.DateTime Analysis { get; set; }
        public System.DateTime Reporting { get; set; }
        public System.DateTime Debrief { get; set; }
        public string KeyInformation { get; set; }
        public string SpecialRequirements { get; set; }
        public Nullable<int> NumDirectorsRequired { get; set; }
        public Nullable<int> NumSeniorManagersRequired { get; set; }
        public Nullable<int> NumManagersRequired { get; set; }
        public Nullable<int> NumSeniorAssociate2Required { get; set; }
        public Nullable<int> NumSeniorAssociate1Required { get; set; }
        public Nullable<int> NumAssociate2Required { get; set; }
        public Nullable<int> NumAssociate1Required { get; set; }
        public Nullable<int> DaysDirectorsRequired { get; set; }
        public Nullable<int> DaysSeniorManagersRequired { get; set; }
        public Nullable<int> DaysManagersRequired { get; set; }
        public Nullable<int> DaysSeniorAssociate2Required { get; set; }
        public Nullable<int> DaysSeniorAssociate1Required { get; set; }
        public Nullable<int> DaysAssociate2Required { get; set; }
        public Nullable<int> DaysAssociate1Required { get; set; }
        public Nullable<System.DateTime> ResponseNeededBy { get; set; }
        public Nullable<int> fk_UserId_Requester { get; set; }
        public string Status { get; set; }
    }
}
